name: Telus CI CD
'on':
  push:
    branches:
      - patch-1
  workflow_dispatch: null
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '16'
          cache: maven

          -name: Build with Maven
          run: mvn -B package --file pom.xml
      #----------------------------------------
      - name: HTML Preview
    id: html_preview
  uses: pavi2410/html-preview-action@v2
  with:
    html_file: 'Index.html'

  #- name: maven build Telus CI
    run: mvn clean install test -DsuiteXmlFile='testng_front.xml'
    working-directory: IgnitionQAAutomation

    #=================================
#      - name: HTML Preview
#          id: html_preview
#          uses: pavi2410/html-preview-action@v2
#          with:
#            html_file: 'Index.html'
