name: Telus CI CD
'on':
  push:
    branches:
      - patch-1
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '16'
          cache: maven
          -name: Build with Maven
          run: mvn -B package --file pom.xml

      - uses: actions/github-script@v6
        id: job-url
        with:
          script: |
            const { data } = await
            github.rest.actions.listJobsForWorkflowRunAttempt({...context.repo,run_id: context.runId,attempt_number: process.env.GITHUB_RUN_ATTEMPT, });
            return data.jobs[0].html_url
          result-encoding: string

      - name: Print Log URL
        run: |
          echo "Log URL: ${{ steps.job-url.outputs.result }}"


      - name: maven build Telus CI
        run: mvn clean install test -DsuiteXmlFile='testng_front.xml'
        working-directory: IgnitionQAAutomation

      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: karthikeyan.armugam@telusagcg.com
          # from email name
          from: automationqaafs@gmail.com






