# This is the original code- don't touch it
name: Telus CI CD
'on':
  push:
    branches:
      - patch-1
  workflow_dispatch: null
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

          -name: Build with Maven
          run: mvn -B package --file pom.xml
      - name: maven build Telus CI
        run: mvn clean install test -DsuiteXmlFile='testng_front.xml'
        working-directory: IgnitionQAAutomation
