name: Igni WMS
on:
 push:
   branches:
     - develop_autom
 workflow_dispatch:
  
jobs:
  get-runner:
    name : WMS Automation
    if: ${{ always() }}
    runs-on: self-hosted
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
      
      
      
      - name: WMS Automation
        run: |
         mvn install test -DsuiteXmlFile='WorkQueueTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
      - name: WMS Automation Install
        run: |
         mvn install
        working-directory: AFS_Automation/WMS_Automation 
        
        
      - name: Add
        if: always()
        run: |
          git add .
          git commit -m "Add"
          git push origin develop_autom
                       
      #- name: build for recent rep-gen
        #run: |
         
         #mvn install test -DsuiteXmlFile='msg_delay_wms.xml'
        #working-directory: AFS_Automation/WMS_Automation
