name: OMS Regression
on:
 push:
    branches:
      - cro

 

jobs:
  job1:
    name : OMS Automation
    runs-on: self-hosted
    
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
      
      
      
      
      - name: OMS Automation module-1
        run: |
         mvn compile
         mvn clean install test -DsuiteXmlFile='TestNG_Admin_Grid_Report_Security_ARinq.xml'
        working-directory: AFS_Automation/OMS_Automation
        
       
# ##########################################################################        
  job2:  
    needs: job1
    name : job2 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-2
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_BillToBill_CustInq_Quote.xml'        
      
      
        
# ##########################################################################        
  job3:  
    needs: job2
    name : job3 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-3
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_Catalog1.xml'
        working-directory: AFS_Automation/OMS_Automation 

        # ##########################################################################        

  
  job4:  
    needs: job3
    name : job4 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-4
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_Catalog2.xml'
        
       
        
      
     
        
# ########################################################################### 


    
  job5:  
    needs: job4
    name : job5 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-5
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_Login_AllOrder.xml'


         # ##########################################################################        
  job6:  
    needs: job5
    name : job6 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-6
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_OE.xml'

         # ##########################################################################        
  job7:  
    needs: job6
    name : job7 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-7
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_OE1.xml'


         # ##########################################################################        

  
  job8:  
    needs: job7
    name : job8 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-8
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_OE2.xml'


          # ##########################################################################        

  
  job9:  
    needs: job8
    name : job9 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-9
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_OE3.xml'


          # ##########################################################################        

  
  job10:  
    needs: job9
    name : job10 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-10
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_OG_PO_ProdRef.xml'

           # ##########################################################################        

  
  job11:  
    needs: job10
    name : job11 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-11
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_SO_Inventory.xml'


         # ##########################################################################        

  
  job12:  
    needs: job11
    name : job12 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: OMS Automation module-12
        run: |
         mvn clean install test -DsuiteXmlFile='TestNG_Statements_WebORder_UserManagement.xml'


          # ########################################################################## 
