name: Telus CI CD

on:
  workflow_dispatch:


jobs:
 
  build:
    
    runs-on:
      - self-hosted
      - label-1


    steps:
      - uses: actions/checkout@v3
      
      
      - name: Run a one-line script
        run:
          echo Hello, world
          sleep 2
          echo Goodbye
