name: Telus CI CD
on:
  workflow_dispatch:
  push:
    branches:
      - patch-1
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: "16"
          distribution: temurin
          cache: maven
      - name: Telus CI
        run: mvn clean test -DsuiteXmlFile='testng.xml'
      - uses: deblockt/cucumber-report-annotations-action@vl.7
        with:
         access-token: ${{ secrets.GITHUB_TOKEN }}
         path: “**/cucumber. json"
      - name: Deploy report page to GitHub Page
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish dir: ./target
          working-directory: IgnitionQAAutomation
        
