name: OMS-D Regression

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        default: main

jobs:
  build:
    name: OMS Automation
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '16'
          cache: maven

      - name: Install Chocolatey if Missing
        run: |
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) 
          {
              Write-Output "Installing Chocolatey..."
              Set-ExecutionPolicy Bypass -Scope Process -Force; \
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
              iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
              $env:PATH += ";C:\ProgramData\chocolatey\bin"
          } 
          else 
          {
              Write-Output "Chocolatey already installed."
          }

      - name: Add Chocolatey to PATH
        run: |
          $env:PATH += ";C:\ProgramData\chocolatey\bin"

      - name: Verify Chocolatey Installation
        run: choco --version

      - name: Verify Maven Installation
        run: mvn -version
        shell: pwsh

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: List files in current directory
        run: dir

      - name: Create cucumber-reports directory
        run: mkdir AFS_Automation/OMS_Automation/target/cucumber-reports

      - name: OMS Automation module-1
        run: >
          mvn clean install test -DsuiteXmlFile='TestNG_Admin_Grid.xml'
          -Dheadless=true
        working-directory: AFS_Automation/OMS_Automation

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: AFS_Automation/OMS_Automation/target/cucumber-reports

  clean-up:
    runs-on: windows-latest
    steps:
      - name: Clean up temporary files
        shell: pwsh
        run: |
          if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
            Write-Error "Administrator privileges are required for cleanup."
            exit 1
          }
          Write-Host "Deleting all files in $env:TEMP"
          Get-ChildItem -Path "$env:TEMP" -Recurse -Force -File | Remove-Item -Force
          Write-Host "Removing all empty folders in $env:TEMP"
          Get-ChildItem -Path "$env:TEMP" -Recurse -Force -Directory |
          Where-Object { $_.GetFiles().Count -eq 0 -and $_.GetDirectories().Count -eq 0 } |
          Remove-Item -Force -Recurse         
