name: OMS-D Regression

on:
 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        default: 'main'

jobs:
  build:
    runs-on: windows-latest
  
  job1:
    name: OMS Automation
    runs-on: self-hosted

    steps:
      - name: Clean up unused images and space
        run: |
          sudo rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/local/lib/android/
          sudo apt-get clean
          df -h

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '16'
          cache: maven

      # Ensure Maven is installed and accessible
      - name: Check Maven version
        run: mvn -v

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # List files to verify the working directory
      - name: List files in current directory
        run: dir  # Use 'ls' for Linux or 'dir' for Windows based on your runner

      # Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Add this step to create the cucumber-reports directory if it doesn't exist
      - name: Create cucumber-reports directory
        run: mkdir -p AFS_Automation/OMS_Automation/target/cucumber-reports  

      # Run OMS Automation module-1 in headless mode
      - name: OMS Automation module-1
        run: |
          mvn clean install test -DsuiteXmlFile='TestNG_Admin_Grid.xml' -Dheadless=true
        working-directory: AFS_Automation/OMS_Automation

      # Upload test results
      - name: Upload test results
        if: success() || failure()  # Ensure that results are uploaded even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/

      # For cleaning all temp files in server	
      - name: Clean up after job
        run: rm -rf /path/to/temp/folder/*
