name: WMS Regression
on:
  schedule:
    - cron:  '15 21 2-30/2 * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        default: 'main'

jobs:
  job1:
    name : WMS Automation
    runs-on: self-hosted


    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml




      - name: WMS -1
        run: |
         mvn install test -DsuiteXmlFile='OutboundOrderSummaryAssignTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation
