name: WMS Regression
on:
 push:
   branches:
     - karthik
 workflow_dispatch:
  
jobs:
  job1:
    name : WMS Automation
    runs-on: self-hosted
    
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
      
      
      
      
      - name: WMS R2402 before API2.0 Migration
        run: |
         mvn install test -DsuiteXmlFile='OutboundLoadPlanning1TestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
       
        
      
      
        
# ##########################################################################        
  job2:  
    needs: job1
    name : job2 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: WMS Automation module-2
        run: |
         mvn install test -DsuiteXmlFile='OutboundLoadPlanning2TestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
       
        
      
     
        
# ###########################################################################        
  job3:  
    needs: job2
    name : job3 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
   
      - name: WMS Automation module-3
        run: |
         mvn install test -DsuiteXmlFile='OutboundLoadPlanning3TestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
       
        
      
              
              # ###########################################################################        
  job4:  
    needs: job3
    name : job4 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
   
      - name: WMS Automation module-4
        run: |
         mvn install test -DsuiteXmlFile='OutboundLoadPlanning4TestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
        # ###########################################################################  

  job47:  
    needs: job4
    name : job47 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
   
      - name: WMS Automation module-47
        run: |
         mvn clean install test -DsuiteXmlFile='DashboardTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation
        
        

# ###########################################################################  
