name: WMS Regression
on:
 push:
   branches:
     - karthik
 workflow_dispatch:
  

jobs:
  job1:
    name : WMS Automation
    runs-on: self-hosted
    
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
      
      
      
      
      - name: WMS Automation module-1
        run: |
         mvn install test -DsuiteXmlFile='InboundLoadsSummary1CucumberTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
       
        
      
      
        
# ##########################################################################        
  job2:  
    needs: job1
    name : job2 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
     
      - name: WMS Automation module-2
        run: |
         mvn install test -DsuiteXmlFile='InboundLoadsSummary2CucumberTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
       
        
      
     
        
# ###########################################################################        
  job3:  
    needs: job2
    name : job3 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
   
      - name: WMS Automation module-3
        run: |
         mvn install test -DsuiteXmlFile='InboundLoadsSummary3CucumberTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
       
        
      
              
              # ###########################################################################        
  job4:  
    needs: job3
    name : job4 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
   
      - name: WMS Automation module-4
        run: |
         mvn install test -DsuiteXmlFile='InboundLoadsSummary4CucumberTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
        # ########################################################################### 


  job5:  
    needs: job4
    name : job5 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
   
      - name: WMS Automation module-5
        run: |
         mvn install test -DsuiteXmlFile='InboundOrdersScreenCucumberTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
        # ########################################################################### 


  job6:  
    needs: job5
    name : job6 name
    if: success() || failure()
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: temurin
           java-version: '16'
           cache: maven
           -name: Build with Maven
           run: mvn -B package --file pom.xml
   
      - name: WMS Automation module-6
        run: |
         mvn install test -DsuiteXmlFile='InboundOrdersDetailsCucumberTestNGRunner.xml'
        working-directory: AFS_Automation/WMS_Automation 
        
        # ###########################################################################
